### ISSUE TITLE
Is the `BoxedSlice<T, N>` any different `Box<[T; N]>`?

### ISSUE THREAD

**Issue by WaffleLapkin** [aspenluxxxy/boxed-slice#2]
What does the `BoxedSlice<T, N>` allow, what `Box<[T; N]>` does not? It seems that they are nearly identical.

**Comment by aspenluxxxy** [comment]
i think i made this as a work-around for serde, because serde doesn't support min-const-generics yet

**Comment by WaffleLapkin** [comment]
I think it would be a good idea to document this. Thanks for the answer.
